# Generated by Django 3.2.7 on 2021-09-18 16:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New course', max_length=256)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('visibility', models.IntegerField(choices=[(1, 'Everyone'), (2, 'Participants'), (3, 'Authors')], default=3, verbose_name='Visibility')),
            ],
        ),
    ]
