# Generated by Django 3.2.7 on 2021-09-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_coursechapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New topic', max_length=256)),
            ],
        ),
    ]
