# Generated by Django 3.2.7 on 2021-09-18 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_coursemaincategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New topic', max_length=256)),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='courses.coursemaincategory', verbose_name='Course')),
            ],
        ),
    ]
