# Generated by Django 3.2.7 on 2021-11-14 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesubcategory',
            name='main_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='courses.coursemaincategory', verbose_name='Main Category'),
        ),
    ]
