# Generated by Django 3.2.7 on 2022-01-10 22:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_courseratingsystem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseratingsystem',
            name='course',
        ),
        migrations.RemoveField(
            model_name='courseratingsystem',
            name='created_at',
        ),
        migrations.CreateModel(
            name='CourseRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('rating', models.IntegerField(default=1, max_length=3, verbose_name='Rating')),
                ('action', models.IntegerField(choices=[(1, 'New comment'), (2, 'New Participant'), (3, 'New Rating'), (4, 'New Rating')], unique=True, verbose_name='Action')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='courses.course', verbose_name='Course')),
            ],
        ),
    ]
