# Generated by Django 3.2.7 on 2022-01-10 23:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20220110_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.IntegerField(default=10, validators=[django.core.validators.MaxValueValidator(200), django.core.validators.MinValueValidator(10)], verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='courseratingsystem',
            name='rating',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Rating'),
        ),
    ]
