# Generated by Django 3.2.7 on 2022-01-10 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20220110_2316'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseRating',
        ),
    ]
