# Generated by Django 3.2.7 on 2022-01-11 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_usercourserating_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseratingsystem',
            name='action',
            field=models.IntegerField(choices=[(1, 'Points for new comment for course owner'), (2, 'Points for new comment for co-creators'), (3, 'Points for new participant for co-creators'), (4, 'Points for new participant for course owner'), (5, 'Points for new rating for course owner'), (6, 'Points for new rating for co-creator'), (7, 'New course owner activity in course'), (8, 'New co-creator activity in course')], unique=True, verbose_name='Action'),
        ),
    ]
