# Generated by Django 3.2.9 on 2022-01-23 15:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_alter_courseratingsystem_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.IntegerField(default=10, validators=[django.core.validators.MaxValueValidator(200), django.core.validators.MinValueValidator(10)], verbose_name='Price'),
        ),
    ]
