# Generated by Django 3.2.7 on 2022-02-07 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_alter_courseratingsystem_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='price',
        ),
    ]
