# Generated by Django 3.2.7 on 2021-11-14 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_coursesubcategory_main_category'),
        ('users', '0003_customuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCoCreator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('co_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_courses', to=settings.AUTH_USER_MODEL, verbose_name='Co-Creator')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='courses.course', verbose_name='Course')),
            ],
        ),
        migrations.DeleteModel(
            name='CourseAuthor',
        ),
    ]
