# Generated by Django 3.2.7 on 2021-11-14 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_creator'),
        ('users', '0004_auto_20211114_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecocreator',
            name='co_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_managed', to=settings.AUTH_USER_MODEL, verbose_name='Co-Creator'),
        ),
        migrations.AlterField(
            model_name='coursecocreator',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_creators', to='courses.course', verbose_name='Course'),
        ),
    ]
