# Generated by Django 3.2.7 on 2022-01-10 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_coursechaptercomment'),
        ('users', '0005_auto_20211114_1816'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseparticipant',
            unique_together={('course', 'participant')},
        ),
    ]
