# Generated by Django 3.2.7 on 2022-01-10 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_courserating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseRating',
            new_name='UserRating',
        ),
    ]
