# Generated by Django 3.2.7 on 2022-02-06 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20220206_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrating',
            name='action',
            field=models.IntegerField(choices=[(1, 'Points for new comment for course owner'), (2, 'Points for new comment for co-creators'), (3, 'Points for new participant for co-creators'), (4, 'Points for new participant for course owner'), (5, 'Points for new rating for course owner'), (6, 'Points for new rating for co-creator'), (7, 'New course owner activity in course'), (8, 'New co-creator activity in course'), (9, 'Points for new follower')], unique=True, verbose_name='Action'),
        ),
    ]
