# Generated by Django 3.2.7 on 2022-02-09 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_alter_course_visibility'),
        ('users', '0013_alter_userrating_action'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursecocreator',
            unique_together={('course', 'co_creator')},
        ),
    ]
